title: Hot Sauce的博客
subtitle: 搬砖中。。。
description: Hot Sauce
author: Hot Sauce
email: henfanren_zz@163.com
keywords: 'js,javascript,开发者,程序猿,程序,极客,编程,代码,开源,IT网站,Developer,Programmer,Coder,撸码,搬砖,码农'
url: //Bored-AnnoYing.github.io
root: /
permalink: ':year/:month/:day/:title/'
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
permalink_defaults: null
source_dir: source
public_dir: public
new_post_name: ':title.md'
default_layout: post
titlecase: false
external_link: true
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
highlight:
  enable: true
  auto_detect: false
  line_number: true
  tab_replace: ''
default_category: uncategorized
category_map: null
tag_map: null
archive: 1
category: 1
tag: 1
port: 4000
server_ip: localhost
logger: false
logger_format: dev
date_format: YYYY-MM-DD
time_format: 'HH:mm:ss'
per_page: 10
pagination_dir: page
disqus_shortname: null
theme: yilia
exclude_generator: null
deploy:
  type: git
  repository: 'git@github.com:Bored-AnnoYing/Bored-AnnoYing.github.io.git'
  branch: master
jsonContent:
  meta: false
  pages: false
  posts:
    title: true
    date: true
    path: true
    text: false
    raw: false
    content: false
    slug: false
    updated: false
    comments: false
    link: false
    permalink: false
    excerpt: false
    categories: false
    tags: true
